// Generated by `pnpm email:types` from the Resend dashboard — do not edit.

export type EmailTemplateVariables = {
  ADMIN_LOGIN: { NAME?: string; VERIFY_URL: string };
  CLIENT_BOOKING_CONFIRMATION: {
    ADD_TO_GOOGLE_CALENDAR_LINK?: string;
    BOOKED_TIME: string;
    NAME?: string;
  };
  DEPOSIT_REQUEST: {
    BOOKED_TIME: string;
    DEPOSIT_AMOUNT?: string;
    NAME?: string;
    SUMMARY_URL: string;
  };
  REMINDER_ON_THE_DAY: { BOOKED_TIME: string; NAME?: string };
  RESCHEDULE_NOTIFICATION: {
    ADD_TO_GOOGLE_CALENDAR_LINK: string;
    BOOKED_TIME: string;
    NAME?: string;
    OLD_TIME: string;
  };
};
