// Generates `EmailTemplateVariables` from the templates stored in the Resend
// dashboard, so a variable renamed there surfaces as a type error here.
// Run with `pnpm email:types` after editing a template, then commit the output.
import 'dotenv/config';
import { writeFileSync } from 'node:fs';

import { RESEND_EMAIL_TEMPLATES } from '@/lib/resend/email-templates';
import { resend } from '@/lib/resend/index';

const OUTPUT_PATH = 'src/lib/resend/email-template-variables.generated.ts';

async function main() {
  const entries: string[] = [];

  for (const [key, id] of Object.entries(RESEND_EMAIL_TEMPLATES)) {
    const { data, error } = await resend.templates.get(id);
    if (error || !data) {
      throw new Error(
        `Failed to fetch template ${key} (${id}): ${error?.message}`,
      );
    }

    if (data.status !== 'published') {
      console.warn(`⚠ ${key}: template is not published`);
    }
    if (data.has_unpublished_versions) {
      console.warn(
        `⚠ ${key}: has unpublished changes — types reflect the latest version`,
      );
    }

    const fields = (data.variables ?? [])
      .toSorted((a, b) => a.key.localeCompare(b.key))
      .map((variable) => {
        const optional = variable.fallback_value !== null ? '?' : '';
        return `${JSON.stringify(variable.key)}${optional}: ${variable.type};`;
      });

    entries.push(`${key}: { ${fields.join(' ')} };`);
    console.log(`✓ ${key}: ${fields.length} variable(s)`);
  }

  const source = `// Generated by \`pnpm email:types\` from the Resend dashboard — do not edit.

export type EmailTemplateVariables = {
${entries.join('\n')}
};
`;

  writeFileSync(OUTPUT_PATH, source);
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
